/*****************************************************/
/*						                             
/*    SAS file: Download_retail_trades.sas           
/*    Input Files: WRDS TAQ databases               
/*    Output Files: taq_&start_date&end_date                    
/*    Author: Matthew Ringgenberg		             
/*    Created Date: 4/03/2017		                 
/*    Revised Date: 7/25/2017			             
/*							                         
/*****************************************************/


/* Initial Setup Commands */
OPTIONS ls=90 ps=55 ;
DM 'clear log';
DM 'clear output';
LIBNAME results "/scratch/utah/MR1";
LIBNAME nbbo '/wrds/nyse/sasdata/taqms/nbbo';
LIBNAME cq '/wrds/nyse/sasdata/taqms/cq';
LIBNAME ct '/wrds/nyse/sasdata/taqms/ct';
%LET outputfile = retail2017;


/* Macro to create database of SAS filenames we want to download */
%macro taq_daily_dataset_list(type=,begyyyymmdd=,endyyyymmdd=) / des="Autogenerated list of needed Daily TAQ datasets";
	%let type=%lowcase(&type);
    /* Get SAS date values for date range endpoints */
    %let begdate = %sysfunc(inputn(&begyyyymmdd,yymmdd8.));
    %let enddate = %sysfunc(inputn(&endyyyymmdd,yymmdd8.));
        %do d=&begdate %to &enddate /** For each date in the DATE range */;
            %let yyyymmdd=%sysfunc(putn(&d,yymmddn8.));
            /*If the corresponding dataset exists, add it to the list */
            %if %sysfunc(exist(ct.&type._&yyyymmdd)) %then ct.&type._&yyyymmdd;
        %end;
%mend;


/* Pull trade data from daily TAQ files */
DATA temp1 (KEEP=SYM_ROOT date time_m price size retail_buy_vol retail_sell_vol);
SET %taq_daily_dataset_list(type=ctm,begyyyymmdd=20170101,endyyyymmdd=20171231) OPEN=DEFER;
WHERE time_m >= '9:30:00.000000000't AND time_m <= '16:00:00.000000000't AND price > 0 AND size > 0 AND tr_corr EQ '00' AND ex = "D";
z = 100*mod(price, .01);
IF z >0 AND z <.4 THEN retail_sell_vol = size;
	ELSE retail_sell_vol = .;
IF z >0.6 AND z <1 THEN retail_buy_vol = size;
	ELSE retail_buy_vol = .;
RUN;

  
/* Sort in preparation of next step */
PROC SORT DATA=temp1;
BY SYM_ROOT date;
RUN;
QUIT;


/* Aggregate to the firm-day level */
PROC MEANS DATA=temp1 NOPRINT;
BY SYM_ROOT date;
VAR size retail_buy_vol retail_sell_vol;
OUTPUT OUT=temp2 (DROP=_type_ _freq_) SUM=total_vol retail_buy_vol retail_sell_vol;
RUN;
QUIT;


/* Clean-up resulting database */
DATA temp2;
SET temp2;
ATTRIB _all_ LABEL='';
RUN; 


/* Sort the database and save a copy of it in the results directory */
PROC SORT DATA=temp2 OUT=results.&outputfile;
BY SYM_ROOT date;
RUN;
QUIT;
